export const options = [
  { value: 'moscow', label: 'Moscow' },
  { value: 'voronezh', label: 'Voronezh' },
  { value: 'lipetsk', label: 'Lipetsk' },
  { value: 'chelyabinsk', label: 'Chelyabinsk' },
  { value: 'sochi', label: 'Sochi' },
  { value: 'novosibirsk', label: 'Novosibirsk' },
  { value: 'vladivostok', label: 'Vladivostok' },
  { value: 'ekaterinburg', label: 'Ekaterinburg' },
  { value: 'petersburg', label: 'St. Petersburg' },
  { value: 'nizhnyNovgorod', label: 'Nizhny Novgorod' },
  { value: 'kazan', label: 'Kazan' },
  { value: 'samara', label: 'Samara' },
  { value: 'omsk', label: 'Omsk' },
  { value: 'ufa', label: 'Ufa' },
  { value: 'belgorod', label: 'Belgorod' },
  { value: 'krasnoyarsk', label: 'Krasnoyarsk' },
  { value: 'perm', label: 'Perm' },
  { value: 'volgograd', label: 'Volgograd' },
  { value: 'saratov', label: 'Saratov' },
  { value: 'tyumen', label: 'Tyumen' },
  { value: 'irkutsk', label: 'Irkutsk' },
  { value: 'yaroslavl', label: 'Yaroslavl' },
  { value: 'tomsk', label: 'Tomsk' },
  { value: 'ryazan', label: 'Ryazan' },
  { value: 'tver', label: 'Tver' },
  { value: 'pechora', label: 'Pechora' },
]
